# Introduction to Numpy

In [1]:
#Import Numpy
import numpy as np

### Creating Numpy Arrays

In [2]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [3]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [17]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Built-in Methods

#### arange

In [15]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

#### zeros and ones

In [19]:
np.zeros(3)

array([0., 0., 0.])

In [21]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [22]:
np.ones(3)

array([1., 1., 1.])

In [23]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### linspace 

In [24]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [25]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

#### eye 

In [26]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### rand 

In [27]:
np.random.rand(2)

array([0.25118918, 0.66089779])

In [28]:
np.random.rand(5,5)

array([[0.22126578, 0.41721011, 0.80211323, 0.73949276, 0.33483302],
       [0.68953303, 0.29225769, 0.64673226, 0.76375813, 0.35163165],
       [0.23433388, 0.38949461, 0.06056739, 0.73195697, 0.31011   ],
       [0.80421865, 0.52399074, 0.51235377, 0.1172852 , 0.57135441],
       [0.54786183, 0.36726921, 0.44055004, 0.1416037 , 0.18668512]])

#### randn 

In [29]:
np.random.randn(2)

array([ 0.26410845, -0.46560728])

In [30]:
np.random.randn(5,5)

array([[-4.75534052e-01,  1.68953499e+00,  1.39237638e+00,
        -1.27414976e+00, -3.19318781e-01],
       [-7.28919353e-01, -2.27199081e-01, -1.83668883e-01,
         1.94976970e+00,  4.82434505e-01],
       [-1.56224366e+00, -6.65116745e-02, -1.37868214e+00,
        -4.02408834e-01, -1.40382276e+00],
       [-8.44949362e-01, -1.42031683e+00,  1.37119970e+00,
        -1.69616598e+00, -2.13209794e-01],
       [ 1.40400509e+00, -9.94074809e-02,  2.01432660e-03,
         2.74603310e+00, -1.11896672e+00]])

#### randint 

In [31]:
np.random.randint(1,100)

23

In [32]:
np.random.randint(1,100,10)

array([32, 33, 12, 59, 13, 85, 89, 20, 19, 20])

In [34]:
np.random.randint(1,100,(10,10))

array([[77, 33, 94,  8, 22, 54,  4, 21, 42, 99],
       [54, 96, 58, 45, 47, 58, 65, 86, 79, 51],
       [93, 84, 41, 83, 48, 86, 17, 35, 44, 74],
       [71, 21, 11, 61, 54, 24, 77, 98, 34, 75],
       [76, 98, 12, 85, 68, 91, 15, 65,  3, 79],
       [64, 36, 67, 28, 59, 20, 22, 95, 46, 40],
       [31, 13, 13, 71, 81, 86, 69, 24, 53, 93],
       [31, 73, 31, 49, 88, 79, 27, 78,  5, 56],
       [10, 10, 73, 45, 16, 82, 64, 62, 82, 20],
       [69, 33, 67, 79, 48, 61, 47, 20, 75, 50]])

#### seed
Used to set the random state, so we can get same result of random

In [35]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [36]:
np.random.rand(4)

array([0.15601864, 0.15599452, 0.05808361, 0.86617615])

In [37]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

## Array Attributes and Methods


In [41]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [43]:
ranarr = np.random.randint(0,50,10)
ranarr

array([21,  1, 23, 43, 29, 37,  1, 20, 32, 11])

#### Reshape
Return array with same data and new shape

In [44]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [45]:
ranarr.reshape(2,5)

array([[21,  1, 23, 43, 29],
       [37,  1, 20, 32, 11]])

#### max, min, argmax, argmin

In [46]:
ranarr

array([21,  1, 23, 43, 29, 37,  1, 20, 32, 11])

In [47]:
ranarr.max()

43

In [49]:
#Find the location / index of max value
ranarr.argmax()

3

In [50]:
ranarr.min()

1

In [51]:
ranarr.argmin()

1

## Shape
shape is attribute of the array, not a method

In [52]:
arr.shape

(25,)

In [53]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [54]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [57]:
arr.reshape(1,25).shape

(1, 25)

In [58]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [59]:
arr.reshape(25,1).shape

(25, 1)

#### dytpe

In [60]:
arr.dtype

dtype('int64')

In [62]:
arr2 = np.array([1.2, 3.4, 5.6])

In [63]:
arr2

array([1.2, 3.4, 5.6])

In [64]:
arr2.dtype

dtype('float64')