## Arithmetic


In [2]:
import numpy as np
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [4]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [5]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
arr**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

## Universal array functions

In [8]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
#taking the square
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [10]:
#calculating expnetial
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [11]:
#Take sin
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

## Summary Statistics on Arrays

In [13]:
arr = np.arange(0,10)

In [14]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
arr.sum()

45

In [16]:
arr.mean()


4.5

In [17]:
arr.max()

9

## Axis Logic


In [18]:
arr_2d = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
arr_2d.sum(axis=0)

array([15, 18, 21, 24])

In [21]:
arr_2d.sum(axis=1)

array([10, 26, 42])

<img src='axis_logic.png' width=400/>