In [2]:
import numpy as np

arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Bracket indexing & selection

In [3]:
arr[8]

8

In [4]:
arr[1:5]

array([1, 2, 3, 4])

In [5]:
arr[0:5]

array([0, 1, 2, 3, 4])

### Broadcasting


In [6]:
arr[0:5] = 100

In [7]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
arr2 = np.arange(0,11)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
slice_of_arr = arr2[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [11]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [12]:
arr2

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

Please note that if we change the value on <b>slice_of_arr</b>, the value of original array is also changed

In [13]:
arr_copy = arr2.copy()
arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [14]:
arr_copy[:] = 12
arr_copy

array([12, 12, 12, 12, 12, 12, 12, 12, 12, 12, 12])

In [15]:
arr2

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

But if we create a copy of array, we can change the new array without change the value of original array

## Indexing 2D array (matric)

In [16]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [17]:
arr_2d[1]

array([20, 25, 30])

In [18]:
arr_2d[1][1]

25

In [19]:
arr_2d[1,1]

25

In [23]:
arr_2d[:,:]

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [25]:
arr_2d[:1]

array([[ 5, 10, 15]])

In [26]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [27]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

### More help about indexing
<img src="numpy_indexing.png" width=500/> Image source: http://www.scipy-lectures.org/intro/numpy/numpy.html

## Conditional Selection

In [28]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [29]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [30]:
bool_arr = arr>4

In [31]:
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [32]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [33]:
arr[arr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [34]:
x = 2

In [35]:
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])